<?php
/**
 * --------------------------------------------------------------------------
 *  File: core/Console/Commands/Make/ViewCommand.php
 *  --------------------------------------------------------------------------
 *  This command generates a new view file inside the /resources/views directory.
 *  View files are used by the Phuel templating engine.
 */

namespace Phuelone\Console\Commands\Make;

use Phuelone\Console\Command;
use Phuelone\Support\Filesystem;

/**
 * Class ViewCommand
 *
 * Creates a new view file at resources/views.
 *
 * Usage:
 *   php phuelone make:view homepage
 *   php phuelone make:view admin/dashboard
 */
class ViewCommand extends Command
{
    /**
     * Command signature recognized by the CLI.
     *
     * @var string
     */
    protected string $signature = 'make:view {name : The name/path of the view (dot or slash format)}';

    /**
     * Handle the creation of a new view file.
     *
     * @return void
     */
    public function handle(): void
    {
        $name = $this->argument('name');

        // Allow dot or slash notation
        $relativePath = str_replace(['.', '\\'], '/', $name) . '.phuel.php';
        $fullPath = base_path("resources/views/{$relativePath}");

        if (Filesystem::exists($fullPath)) {
            $this->error("View '{$name}' already exists.");
            return;
        }

        $stub = $this->defaultStub($name);

        Filesystem::put($fullPath, $stub);

        $this->success("View '{$name}' created at resources/views/");
    }

    /**
     * Returns a default empty view stub.
     *
     * @param string $name
     * @return string
     */
    protected function defaultStub(string $name): string
    {
        return <<<PHP
<!-- View: {$name} -->

<h1>{$name} view</h1>
<p>This view was generated by the CLI.</p>
PHP;
    }
}

?>